function [signal, filteredAmplitudes] = ...
    flatTopReconstruction( ...
        frequencies, ...
        amplitudes, ...
        samplingFrequency, ...
        tau, ...
        time
    )

    samplingPeriod = 1 / samplingFrequency;

    % Filtro ideal
    pulse = samplingPeriod * ...
        (abs(frequencies) <= samplingFrequency / 2);

    % Espectro após o filtro
    filteredAmplitudes = ...
        amplitudes .* pulse;

    % Transformada de Fourier inversa
    signal = zeros(size(time));

    for n = 1:length(time)
        signal(n) = sum( ...
            filteredAmplitudes .* ...
            exp(1j * 2*pi * frequencies * ...
            (time(n) + tau/2)));
    end

    signal = real(signal);
end
