function runSamplingCase( ...
        caseLabel, ...
        caseSuffix, ...
        frequency, ...
        samplingFrequency, ...
        startTime, endTime, numPoints, ...
        outputPath ...
    )
    % runSamplingCase - Executa a análise analítica completa de amostragem
    % (ideal, natural, topo-plano) e reconstrução para um par (frequency,
    % samplingFrequency), e salva todas as figuras em PNG.
    %
    % caseLabel: texto descritivo usado nos títulos (ex: 'Nyquist Respeitado')
    % caseSuffix: sufixo usado nos nomes de arquivo (ex: 'nyquist_ok')
    % Se frequency > samplingFrequency/2, ocorre aliasing e um overlay
    % tracejado com o sinal original é adicionado às reconstruções.

    isAliasing = frequency > samplingFrequency / 2;

    omega = 2 * pi * frequency;
    samplingPeriod = 1 / samplingFrequency;
    tau = 0.2 * samplingPeriod;
    displayRange = 4 * samplingFrequency;
    kMax = ceil((displayRange + frequency) / samplingFrequency);

    x = @(t) sin(omega * t);
    continuousTime = linspace(startTime, endTime, numPoints);
    continuousSignal = x(continuousTime);
    continuousFrequencies = [-frequency, frequency];
    continuousAmplitudes = [0.5j, -0.5j];

    fprintf('  Caso: %s (f=%.1f Hz, fs=%.1f Hz)%s\n', ...
        caseLabel, frequency, samplingFrequency, ...
        merge(isAliasing, ' [ALIASING]', ''));

    % ---------------------------------------------------------------
    % AMOSTRAGEM
    % ---------------------------------------------------------------

    % Ideal
    [idealSignal, idealTime] = idealSampling(x, samplingFrequency, startTime, endTime);
    [idealAmplitudes, idealFrequencies] = idealTransform(frequency, samplingFrequency, kMax);

    figIdeal = plotSamplingFigure( ...
        sprintf('Amostragem Ideal - %s', caseLabel), ...
        continuousTime, continuousSignal, ...
        idealTime, idealSignal, ...
        continuousFrequencies, continuousAmplitudes, ...
        idealFrequencies, idealAmplitudes, ...
        displayRange, ...
        'Amostragem Ideal (Tempo)', 'r', 'stem', ...
        [0 (0.5*samplingFrequency)+2], ...
        [], []);

    % Natural
    [naturalSignal, naturalTime] = naturalSampling(x, samplingFrequency, tau, startTime, endTime, numPoints);
    [naturalAmplitudes, naturalFrequencies] = naturalTransform(frequency, samplingFrequency, tau, kMax);

    figNatural = plotSamplingFigure( ...
        sprintf('Amostragem Natural - %s', caseLabel), ...
        continuousTime, continuousSignal, ...
        naturalTime, naturalSignal, ...
        continuousFrequencies, continuousAmplitudes, ...
        naturalFrequencies, naturalAmplitudes, ...
        displayRange, ...
        'Amostragem Natural (Tempo)', 'b', 'plot', ...
        [], [], []);

    % Topo-plano
    [flatTopSignal, flatTopTime] = flatTopSampling(x, samplingFrequency, tau, startTime, endTime, numPoints);
    [flatTopAmplitudes, flatTopFrequencies] = flatTopTransform(frequency, samplingFrequency, tau, kMax);

    sincEnvelopeFrequency = -displayRange:samplingPeriod:displayRange;
    flatTopEnvelope = abs((tau / samplingPeriod) * sinc(sincEnvelopeFrequency * tau) * 0.5j);

    figFlatTop = plotSamplingFigure( ...
        sprintf('Amostragem Topo-Plano - %s', caseLabel), ...
        continuousTime, continuousSignal, ...
        flatTopTime, flatTopSignal, ...
        continuousFrequencies, continuousAmplitudes, ...
        flatTopFrequencies, flatTopAmplitudes, ...
        displayRange, ...
        'Amostragem Topo-Plano (Tempo)', 'r', 'plot', ...
        [], sincEnvelopeFrequency, flatTopEnvelope);

    % ---------------------------------------------------------------
    % RECONSTRUÇÃO
    % ---------------------------------------------------------------

    % Janela de zoom para deixar visível o aliasing: ~4 períodos do sinal
    % original (o de frequência mais alta entre original e reconstruído)
    if isAliasing
        zoomEndTime = min(endTime, startTime + 4 / frequency);
    else
        zoomEndTime = [];
    end

    [idealReconstructionSignal, filteredIdealAmplitudes] = idealReconstruction( ...
        idealFrequencies, idealAmplitudes, samplingFrequency, continuousTime);

    figReconIdeal = plotReconstructionFigure( ...
        sprintf('Reconstrução Ideal - %s', caseLabel), ...
        continuousTime, continuousSignal, ...
        idealReconstructionSignal, ...
        idealFrequencies, filteredIdealAmplitudes, ...
        displayRange, startTime, endTime, ...
        'r', [0 0.6], isAliasing, zoomEndTime);

    [naturalReconstructionSignal, filteredNaturalAmplitudes] = naturalReconstruction( ...
        naturalFrequencies, naturalAmplitudes, samplingFrequency, tau, continuousTime);

    figReconNatural = plotReconstructionFigure( ...
        sprintf('Reconstrução Natural - %s', caseLabel), ...
        continuousTime, continuousSignal, ...
        naturalReconstructionSignal, ...
        naturalFrequencies, filteredNaturalAmplitudes, ...
        displayRange, startTime, endTime, ...
        'b', [0 0.6], isAliasing, zoomEndTime);

    [flatTopReconstructionSignal, filteredFlatTopAmplitudes] = flatTopReconstruction( ...
        flatTopFrequencies, flatTopAmplitudes, samplingFrequency, tau, continuousTime);

    figReconFlatTop = plotReconstructionFigure( ...
        sprintf('Reconstrução Topo-Plano - %s', caseLabel), ...
        continuousTime, continuousSignal, ...
        flatTopReconstructionSignal, ...
        flatTopFrequencies, filteredFlatTopAmplitudes, ...
        displayRange, startTime, endTime, ...
        'r', [0 0.6], isAliasing, zoomEndTime);

    % ---------------------------------------------------------------
    % SALVAR
    % ---------------------------------------------------------------

    saveFigurePng(figIdeal, fullfile(outputPath, sprintf('sampling_ideal_%s.png', caseSuffix)));
    saveFigurePng(figNatural, fullfile(outputPath, sprintf('sampling_natural_%s.png', caseSuffix)));
    saveFigurePng(figFlatTop, fullfile(outputPath, sprintf('sampling_flattop_%s.png', caseSuffix)));
    saveFigurePng(figReconIdeal, fullfile(outputPath, sprintf('reconstruction_ideal_%s.png', caseSuffix)));
    saveFigurePng(figReconNatural, fullfile(outputPath, sprintf('reconstruction_natural_%s.png', caseSuffix)));
    saveFigurePng(figReconFlatTop, fullfile(outputPath, sprintf('reconstruction_flattop_%s.png', caseSuffix)));
end

function result = merge(condition, valueIfTrue, valueIfFalse)
    if condition
        result = valueIfTrue;
    else
        result = valueIfFalse;
    end
end
