function [flatTopSignal, filteredFlatTopMagnitudes] = ...
    FlatTopReconstruction( ...
        flatTopFrequencyLocations, ...
        flatTopMagnitudes, ...
        samplingFrequency, ...
        tau, ...
        time)

    Ts = 1 / samplingFrequency;

    % Filtro ideal
    pulse = Ts * ...
        (abs(flatTopFrequencyLocations) <= samplingFrequency / 2);

    % Espectro após o filtro
    filteredFlatTopMagnitudes = ...
        flatTopMagnitudes .* pulse;

    % Transformada de Fourier inversa
    flatTopSignal = zeros(size(time));

    for n = 1:length(time)
        flatTopSignal(n) = sum( ...
            filteredFlatTopMagnitudes .* ...
            exp(1j * 2*pi * flatTopFrequencyLocations * ...
            (time(n) + tau/2)));
    end

    flatTopSignal = real(flatTopSignal);

end
